# C-a for prefix
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# C-a r t reload config
bind-key r source-file .config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Use Vi mode for scrolling and searching
set-window-option -g mode-keys vi

# 'v' for select and 'y' for copy (like vi), sync to macOS clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Navigate panes vi style
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

# Start counting at 1 (not 0)
set-option -g base-index 1

# Increase scrollback buffer (default is often too small)
set-option -g history-limit 5000

# https://unix.stackexchange.com/q/608142/112394
set-option -sg escape-time 10

# Recommendation from nvim checkhealth
set-option -g focus-events on

# Plugins
# https://draculatheme.com/tmux
set-option -g @plugin 'dracula/tmux'
set-option -g @dracula-plugins 'network-bandwidth cpu-usage ram-usage'
set-option -g @dracula-show-left-icon "#h | #S"

# Load tmux plugins
run -b '~/.tmux/plugins/tpm/tpm'

