# https://unix.stackexchange.com/q/608142/112394
set-option -sg escape-time 10

# Recommendation from nvim checkhealth
set-option -g focus-events on

# Use Vi mode for scrolling and searching
set-window-option -g mode-keys vi

# Sync to system clipboard (macOS)
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# Increase scrollback buffer (default is often too small)
set-option -g history-limit 5000

# Plugins
# https://draculatheme.com/tmux
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins 'network-bandwidth cpu-usage ram-usage'

# Load tmux plugins
run -b '~/.tmux/plugins/tpm/tpm'

