# Replaces placeholders like {{foo}} with the content of a file called foo
# in the same directory.
#
# Generated by Gemini
#
function include_files \
    --description 'Replace {{filename}} placeholders with file contents'

    # 1. Validate arguments. We need at least the input file.
    if test (count $argv) -lt 1
        echo "Error: Please provide an input file." >&2
        echo "Usage: include_files input_file.txt [output_file.txt]" >&2
        return 1
    end

    set -l input_file $argv[1]
    
    # 2. Write output to the second argument if provided, or to stdout.
    set -l output_file "/dev/stdout"
    if test (count $argv) -ge 2
        set output_file $argv[2]
    end

    # 3. Check if the input file exists.
    if not test -f $input_file
        echo "Error: Input file '$input_file' not found." >&2
        return 1
    end

    # 4. Read the input file into a list of lines.
    set -l doc (cat $input_file)

    # 5. Process placeholders in a loop.
    while true
        # Find the first placeholder like {{filename}} in the document.
        # We quote $doc so fish joins the lines with spaces, letting us
        # search the entire document text at once.
        set -l placeholder (string match -r -- '\{\{[^}]+\}\}' "$doc")[1]
        
        # If no placeholders are left, we are done.
        if test -z "$placeholder"
            break
        end

        # Clean the braces to get the filename (e.g. {{file}} -> file)
        set -l filename (string match -r -- '[^{}]+' $placeholder)

        # Replace the placeholder.
        if test -f $filename
            # Read the file's content as a single string preserving newlines.
            # 'string collect' keeps newlines so we can insert it intact.
            set -l content (cat $filename | string collect)
            set doc (string replace -a -- $placeholder "$content" $doc)
        else
            echo "Warning: Placeholder $placeholder found, but" \
                 "file '$filename' does not exist. Skipping." >&2
            set doc (string replace -a -- $placeholder \
                "NOT_FOUND:$filename" $doc)
        end
    end

    # 6. Output the final processed document.
    printf '%s\n' $doc > $output_file
end
