# Replaces placeholders like {{foo}} with the content of a file called foo in the same directory
#
# AI slop generated by Gemini
#
function include_files --description 'Substitute {{filename}} placeholders with actual file contents'
    # Check if an input file was provided
    if test (count $argv) -lt 1
        echo "Error: Please provide an input file." >&2
        echo "Usage: include_files input_file.txt [output_file.txt]" >&2
        return 1
    end

    set -l input_file $argv[1]
    
    # If a second argument is provided, write to that file; otherwise, output to stdout
    set -l output_file "/dev/stdout"
    if test (count $argv) -ge 2
        set output_file $argv[2]
    end

    if not test -f $input_file
        echo "Error: Input file '$input_file' not found." >&2
        return 1
    end

    # Create a temporary copy of the input file to work with during iterations
    set -l temp_file (mktemp)
    cat $input_file > $temp_file

    # Loop to find placeholders. It extracts anything inside {{...}}
    while true
        set -l file_content (cat $temp_file)
        set -l placeholder (string match -r -- '\{\{[^}]+\}\}' "$file_content")[1]
        
        # If no more placeholders are found, break the loop
        if test -z "$placeholder"
            break
        end

        # Clean the braces to get the actual filename (e.g., {{my-file1}} -> my-file1)
        set -l filename (string match -r -- '[^{}]+' $placeholder)

        # Check if the target file exists in the current directory
        if test -f $filename
            # Use awk with literal index matching instead of regex gsub
            set -l next_temp (mktemp)
            awk -v placeholder="$placeholder" -v file="$filename" '
                BEGIN {
                    # Slurp the external file content into a variable
                    while ((getline line < file) > 0) {
                        content = content (content == "" ? "" : ORS) line
                    }
                    close(file)
                }
                {
                    # Safely replace all literal occurrences of the placeholder in the current line
                    line = $0
                    len = length(placeholder)
                    while ((idx = index(line, placeholder)) > 0) {
                        line = substr(line, 1, idx - 1) content substr(line, idx + len)
                    }
                    print line
                }
            ' $temp_file > $next_temp
            
            mv $next_temp $temp_file
        else
            echo "Warning: Placeholder $placeholder found, but file '$filename' does not exist. Skipping." >&2
            set -l next_temp (mktemp)
            string replace -a -- $placeholder "NOT_FOUND:$filename" < $temp_file > $next_temp
            mv $next_temp $temp_file
        end
    end

    # Output the final result
    cat $temp_file > $output_file
    rm $temp_file
end
